-- 006_uq_patient_slot.sql — 환자 1인 동시 예약 금지 (2026-07-28 chore, FR-15 보강).
-- FR-15 의 가용성 단위는 (의사, 30분 슬롯)이라 **환자 기준** 중복이 통과했다: 한 환자가 같은
-- 시각에 서로 다른 의사로 두 번 예약할 수 있었다(라이브 실측 — 박지훈 2026-07-28 09:00 KST,
-- appointment id 68·69, doctor 3·4 둘 다 '대기'). 사람은 같은 시각에 두 진료를 받을 수 없다.
--
-- 왜 앱 게이트(db/availability.py)가 아니라 DB 제약인가:
--   ① 코드가 더 적다 — 게이트 조각을 한 벌 더 만들어 INSERT 문 둘에 얹는 대신 인덱스 하나.
--   ② 앱 게이트가 못 막는 동시 요청 경쟁(TOCTOU)까지 닫힌다(AD-4 가 명시적 범위 밖으로 둔 것).
--
-- reserved_at 을 그대로 인덱스 키로 쓴다 — 003 의 30분 격자 CHECK 가 걸려 있어 raw 컬럼이 곧
-- 슬롯이다. date_bin 식을 넣을 필요가 없다(식 인덱스의 immutability 제약도 회피).
-- ⚠️ 단, 003 의 보증은 무조건이 아니다: CHECK 가 extract(minute from reserved_at) 기반이라
-- **정시 오프셋 tz(KST 등)에서만** tz-불변이다(003 헤더가 스스로 단 조건). 앱이 쓰는 값은 항상
-- to_slot() 으로 floor 한 UTC 라 raw == date_bin 이지만, 앱 밖에서(SQL 에디터·데이터 보정·임포터)
-- 비정시 오프셋 세션으로 넣은 행은 CHECK 를 통과하고도 floor 결과가 달라질 수 있다. 그때는
-- 이 인덱스와 db/availability.py 의 게이트가 "같은 슬롯"을 서로 다르게 본다(AD-3 경계).
--
-- 부분 인덱스(활성만): 취소·완료는 키에서 빠져 슬롯이 자연히 해제된다 — 2.2 status 전이가
-- "별도 해제 로직 없음"으로 성립하는 것과 같은 규약이다(취소=해제, 완료=무관).
--
-- 경계 ①(정직): walk-in 기록(medical_record.appointment_id null)은 이 인덱스가 못 본다 — 단일
-- 테이블 제약이라서다. 2026-07-28 적용 시점 그 행은 0건이었고, 전용 walk-in 경로는 같은 날
-- correct-course 로 철회됐다(FR-16 축소). 다만 medical_record.appointment_id 는 여전히 nullable
-- 이고 db/medical_records.py 가 여전히 쓸 수 있다 — "0건"은 그때의 관측이지 보증이 아니다.
-- 전용 경로를 되살린다면 앱 게이트 쪽 형제 조건이 필요하다.
--
-- 경계 ②(정직): 술어가 활성(대기·확정)이라 **완료도 키에서 빠진다**. 미래 예약을 미리 완료
-- 처리하면(기록 생성에 "예약 시각 도래" 가드가 없다) 그 환자가 같은 미래 슬롯을 다른 의사로 다시
-- 예약할 수 있다 — 위 "사람은 같은 시각에 두 진료를 받을 수 없다"가 그 경로에선 성립하지 않는다.
-- 데모에서 도달할 이유가 없어 보류했다(deferred-work.md, 2026-07-28 리뷰).
--
-- 근거: FR-15·FR-15b(epics.md), ARCHITECTURE-SPINE.md AD-4.
-- (재적용 안전: `if not exists` — 001·002·003·005 와 동일한 idempotent 정책. 004 는 시드라 마이그레이션이
--  아니다. 002 의 부분 유니크 인덱스와 같은 관용구.)
--
-- ⚠️ 선행 조건 — 기존 위반 행이 있으면 **생성이 실패한다**(`if not exists` 는 이름만 보므로 보호가
-- 안 된다). 001→006 을 새 DB 에 재생할 때는 아래로 먼저 탐지하고, 남길 행을 사람이 정해 지운다.
-- 자동 삭제는 넣지 않는다 — 어느 쪽이 정당한 예약인지는 데이터가 아니라 사람이 안다.
--
--   select patient_id, reserved_at, count(*), array_agg(id order by id) as ids
--   from public.appointment
--   where status in ('대기', '확정')
--   group by patient_id, reserved_at
--   having count(*) > 1
--   order by reserved_at;
--
-- 2026-07-28 라이브 적용 시 이 쿼리가 1그룹(박지훈 09:00 KST, id 68·69)을 냈고 둘 다 삭제했다
-- (검증 데이터 원복 규율 — 처방 → 기록 → 예약 순, id 지정).

create unique index if not exists uq_appointment_patient_slot
  on public.appointment (patient_id, reserved_at)
  where status in ('대기', '확정');
