-- 계모임 스키마 (PRD §5.1)
-- 적용: Supabase SQL Editor 또는 MCP. 재실행 가능(if not exists).

create table if not exists users (
  id         bigint generated by default as identity primary key,
  login_id   text not null unique,
  password   text not null,                 -- 데모용 평문. PRD §6 참조 — 의도된 선택
  nickname   text not null,
  created_at timestamptz not null default now()
);

create table if not exists groups (
  id          bigint generated by default as identity primary key,
  name        text not null,
  summary     text not null,
  description text not null default '',
  category    text not null,                -- TS 상수와 문자열로 대응 (테이블 아님)
  region      text not null,
  owner_id    bigint not null references users(id) on delete cascade,
  created_at  timestamptz not null default now()
);

create table if not exists memberships (
  id        bigint generated by default as identity primary key,
  group_id  bigint not null references groups(id) on delete cascade,
  user_id   bigint not null references users(id) on delete cascade,
  role      text not null default 'member' check (role in ('owner', 'member')),
  joined_at timestamptz not null default now(),
  unique (group_id, user_id)               -- 중복 가입 차단 (PRD R4)
);

create table if not exists events (
  id         bigint generated by default as identity primary key,
  group_id   bigint not null references groups(id) on delete cascade,
  title      text not null,
  starts_at  timestamptz not null,
  place      text not null,
  created_by bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists attendances (
  id         bigint generated by default as identity primary key,
  event_id   bigint not null references events(id) on delete cascade,
  user_id    bigint not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (event_id, user_id)               -- 중복 참석 차단
);

-- 인덱스: 홈 필터(카테고리·지역·최신순)와 상세(멤버·정모) 경로만
create index if not exists idx_groups_category   on groups (category);
create index if not exists idx_groups_region     on groups (region);
create index if not exists idx_groups_created_at on groups (created_at desc);
create index if not exists idx_memberships_group on memberships (group_id);
create index if not exists idx_memberships_user  on memberships (user_id);
create index if not exists idx_events_group      on events (group_id, starts_at);
create index if not exists idx_attendances_event on attendances (event_id);

-- RLS deny-by-default: 정책을 0개로 둔다.
-- 모든 접근은 서버(service_role)를 경유하며 service_role은 RLS를 우회한다.
-- anon 정책을 추가하면 브라우저에서 DB가 직접 열린다 — 추가 금지.
alter table users       enable row level security;
alter table groups      enable row level security;
alter table memberships enable row level security;
alter table events      enable row level security;
alter table attendances enable row level security;
